### ISSUE TITLE
Add filter to see places available on specified date range

### ISSUE THREAD

**Issue by termosa** [Litvinov1618/place-me#3]
- [x] Date range should be selected via calendar

**Comment by Litvinov1618** [comment]
- [x] Use offline filtering
- [x] Add defaultValue to DatePicker
- [x] Make a group of buttons
- [x] Convert seats value to a number
- [x] Think of filterPlaces function name
- [x] Add a object of filters to filterPlaces parameters
- [x] Add custom type instead of DateRange
- [x] Create Places component
